services:
  web:
    build:
      context: ./src/
      dockerfile: Dockerfile
    entrypoint: /app/start-reload.sh
    container_name: web-container
    depends_on:
      db:
        condition: service_healthy
        restart: true
      idprovider:
        condition: service_started
    restart: always
    volumes:
      - ./src:/app
    ports:
      - 7080:80
    environment:
      PROJECT_ENVIRONMENT: dev
      PROJECT_DATABASE_NAME: project
      PROJECT_DATABASE_USER: admin
      PROJECT_DATABASE_PASSWORD: admin
      PROJECT_DATABASE_HOST: db
      PROJECT_DATABASE_PORT: 5432
      PROJECT_ADMIN_PATH: 'secret/'
      KEYCLOAK_URL: 'http://idprovider:8080/realms/test/.well-known/openid-configuration'
      KEYCLOAK_CLIENT_ID: 'develop-client'
      KEYCLOAK_CLIENT_SECRET: 'GF4Hn2RhI8zfWe8WSPIgvgA9kYG4htkF'
      DJANGO_SECRET_KEY: '+80bii=$%g+7tn8s9s(*3)v)_exz2t38^@%-p_q7s4)c+)jb8m'
  
  db:
    image: postgres
    container_name: postgres-container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: project
    ports:
      - '5432:5432'
    volumes: 
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
  
  idprovider:
    image: quay.io/keycloak/keycloak
    command: start-dev --import-realm
    container_name: idprovider-container
    restart: always
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_URL: "http://localhost:8080"
      KC_HOSTNAME_STRICT: "false"
      KC_HTTPS_CERTIFICATE_FILE: "/certs/cert.pem"
      KC_HTTPS_CERTIFICATE_KEY_FILE: "/certs/key.pem"
    ports:
      - '8080:8080'
    volumes:
      - keycloak-data:/opt/keycloak/data
      - ./keycloak/certs:/certs:ro
      - ./keycloak/realms:/opt/keycloak/data/import

volumes:
  db-data:
  keycloak-data: